import { ScopedThemeProvider } from '@syahakato/themes/providers';
import React from 'react';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ readonly children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <ScopedThemeProvider context="app-settings">{children}</ScopedThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
